class BalanceSheet:
    
    def __init__(self, data = None):
        self.AccountsPayable = data.get("AccountsPayable")
        self.AccountsReceivablesTradeNet = data.get("AccountsReceivablesTradeNet")
        self.AccruedExpenses = data.get("AccruedExpenses")
        self.AccumulatedDepreciationTotal = data.get("AccumulatedDepreciationTotal")
        self.AdditionalPaidInCapital = data.get("AdditionalPaidInCapital")
        self.CapitalLeaseObligations = data.get("CapitalLeaseObligations")
        self.Cash = data.get("Cash")
        self.CashEquivalents = data.get("CashEquivalents")
        self.CashandShortTermInvestments = data.get("CashandShortTermInvestments")
        self.CommonStockTotal = data.get("CommonStockTotal")
        self.CurrentPortofLTDebtCapitalLeases = data.get("CurrentPortofLTDebtCapitalLeases")
        self.DeferredIncomeTax = data.get("DeferredIncomeTax")
        self.ESOPDebtGuarantee = data.get("ESOPDebtGuarantee")
        self.GoodwillNet = data.get("GoodwillNet")
        self.IntangiblesNet = data.get("IntangiblesNet")
        self.LongTermDebt = data.get("LongTermDebt")
        self.LongTermInvestments = data.get("LongTermInvestments")
        self.MinorityInterest = data.get("MinorityInterest")
        self.NoteReceivableLongTerm = data.get("NoteReceivableLongTerm")
        self.NotesPayableShortTermDebt = data.get("NotesPayableShortTermDebt")
        self.OtherAssetsTotal = data.get("OtherAssetsTotal")
        self.OtherCurrentAssetsTotal = data.get("OtherCurrentAssetsTotal")
        self.OtherCurrentliabilitiesTotal = data.get("OtherCurrentliabilitiesTotal")
        self.OtherEquityTotal = data.get("OtherEquityTotal")
        self.OtherLiabilitiesTotal = data.get("OtherLiabilitiesTotal")
        self.OtherLongTermAssetsTotal = data.get("OtherLongTermAssetsTotal")
        self.PayableAccrued = data.get("PayableAccrued")
        self.PeriodEnding = data.get("PeriodEnding")
        self.PreferredStockNonRedeemableNet = data.get("PreferredStockNonRedeemableNet")
        self.PrepaidExpenses = data.get("PrepaidExpenses")
        self.PropertyPlantEquipmentTotalGross = data.get("PropertyPlantEquipmentTotalGross")
        self.PropertyPlantEquipmentTotalNet = data.get("PropertyPlantEquipmentTotalNet")
        self.RedeemablePreferredStockTotal = data.get("RedeemablePreferredStockTotal")
        self.RetainedEarningsAccumulatedDeficit = data.get("RetainedEarningsAccumulatedDeficit")
        self.ShortTermInvestments = data.get("ShortTermInvestments")
        self.TotalAssets = data.get("TotalAssets")
        self.TotalCommonSharesOutstanding = data.get("TotalCommonSharesOutstanding")
        self.TotalCurrentAssets = data.get("TotalCurrentAssets")
        self.TotalCurrentLiabilities = data.get("TotalCurrentLiabilities")
        self.TotalEquity = data.get("TotalEquity")
        self.TotalInventory = data.get("TotalInventory")
        self.TotalLiabilities = data.get("TotalLiabilities")
        self.TotalLiabilitiesShareholdersEquity = data.get("TotalLiabilitiesShareholdersEquity")
        self.TotalLongTermDebt = data.get("TotalLongTermDebt")
        self.TotalPreferredSharesOutstanding = data.get("TotalPreferredSharesOutstanding")
        self.TotalReceivablesNet = data.get("TotalReceivablesNet")
        self.TreasuryStockCommon = data.get("TreasuryStockCommon")
        self.UnrealizedGainLoss = data.get("UnrealizedGainLoss")
        
    def to_dict(self):
        return self.__dict__